apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: spark-consumer
        image: catarinafelixcr/iacd-spark-consumer:v1
        # O CMD do teu Dockerfile já executa o spark-submit, por isso não precisamos de mais nada.