apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-consumer
  labels:
    app: spark-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-consumer
  template:
    metadata:
      labels:
        app: spark-consumer
    spec:
      containers:
      - name: consumer
        image: spark-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED  # para o output do python aparecer nos logs logo
          value: "1"
